# This section will apply to all profiles
spring:
    profiles.active: ${czActiveProfile}
    application:
            name: czws
    devtools.restart.enabled: true
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQL5Dialect
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    mvc.dispatch-options-request: true
server.port: 9000
swagger:
    enabled: true
logging:
    config: classpath:logback.xml
cors.allow:
    origins: "*"
    methods: "*"
redis:
    host : localhost
    password:
    port : 6379
    expire : 1800

---

# This section will apply only to dev profile
spring:
    profiles: dev
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://localhost:3306/catchzombie?autoReconnect=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: rootroot
        testWhileIdle: true
        validationQuery: SELECT 1


