# This section will apply to all profiles
spring:
    profiles.active: ${activeProfile}
    devtools.restart.enabled: true
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQL5Dialect
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    mvc.dispatch-options-request: true
server.port: 9000
cors.allow:
    origins: "*"
    methods: "*"